### ISSUE TITLE
pip install fails due to missing requirements.txt

### ISSUE THREAD

**Issue by tobiasschuelke** [nathan-toubiana/scitime#61]
The installations of versions 0.1.1 and 0.1.0 fail because the file requirements.txt is not included in the package. The last working version is 0.0.2.

To reproduce install scitime via pip:

> pip install scitime

This results in:

> Collecting scitime
  Downloading scitime-0.1.1.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pf159ay4/scitime_44b116adacfa47d9a4168d681a1353df/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pf159ay4/scitime_44b116adacfa47d9a4168d681a1353df/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wrkgk825
         cwd: /tmp/pip-install-pf159ay4/scitime_44b116adacfa47d9a4168d681a1353df/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pf159ay4/scitime_44b116adacfa47d9a4168d681a1353df/setup.py", line 14, in <module>
        with open(path.join(DIR, 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-pf159ay4/scitime_44b116adacfa47d9a4168d681a1353df/requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/03/56/172df6aa430f53352c6d50f1d00493ebceef83d8d2b86bbfe2d44b602669/scitime-0.1.1.tar.gz#sha256=6981eff3f8eac835762c6b64d5a123bb8f785229d85eb47855e4b721737aaf3f (from https://pypi.org/simple/scitime/) (requires-python:>=3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading scitime-0.1.0.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pf159ay4/scitime_9d26fb1176f54848896cf05e20c10e9d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pf159ay4/scitime_9d26fb1176f54848896cf05e20c10e9d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kgfl0z_7
         cwd: /tmp/pip-install-pf159ay4/scitime_9d26fb1176f54848896cf05e20c10e9d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pf159ay4/scitime_9d26fb1176f54848896cf05e20c10e9d/setup.py", line 14, in <module>
        with open(path.join(DIR, 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-pf159ay4/scitime_9d26fb1176f54848896cf05e20c10e9d/requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/30/f4/c3639829316ab3819453dac4ae5dcc8770d544c35496c738415bdc7420e4/scitime-0.1.0.tar.gz#sha256=e846f360cd185902cc7b81a4f88921ec522d8c891bf04df316d7878aa4e9e504 (from https://pypi.org/simple/scitime/) (requires-python:>=3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading scitime-0.0.2-py3-none-any.whl (45.9 MB)
     |████████████████████████████████| 45.9 MB 2.0 MB/s
Collecting psutil>=5.4.7
  Downloading psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
     |████████████████████████████████| 296 kB 1.8 MB/s
Collecting joblib>=0.12.5
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
     |████████████████████████████████| 303 kB 1.8 MB/s
Collecting scikit-learn>=0.19.1
  Downloading scikit_learn-0.24.2-cp38-cp38-manylinux2010_x86_64.whl (24.9 MB)
     |████████████████████████████████| 24.9 MB 219 kB/s
Collecting pandas>=0.20.3
  Downloading pandas-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
     |████████████████████████████████| 11.7 MB 2.1 MB/s
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 2.5 MB/s
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 2.4 MB/s
Collecting numpy>=1.17.3
  Downloading numpy-1.21.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
     |████████████████████████████████| 15.8 MB 2.6 MB/s
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.2.0-py3-none-any.whl (12 kB)
Collecting scipy>=0.19.1
  Downloading scipy-1.7.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.4 MB)
     |████████████████████████████████| 28.4 MB 269 kB/s
Installing collected packages: six, numpy, threadpoolctl, scipy, pytz, python-dateutil, joblib, scikit-learn, psutil, pandas, scitime
Successfully installed joblib-1.0.1 numpy-1.21.1 pandas-1.3.1 psutil-5.8.0 python-dateutil-2.8.2 pytz-2021.1 scikit-learn-0.24.2 scipy-1.7.1 scitime-0.0.2 six-1.16.0 threadpoolctl-2.2.0

**Comment by Yarxin** [comment]
I have figured out that the lastest version can be installed using this command:
`python -m pip install git+https://github.com/scitime/scitime`

Should work for you!
